[workspace]
authors = ["Doug Latornell <dlatornell@eoas.ubc.ca>"]
channels = ["conda-forge"]
name = "analysis-doug"
platforms = ["linux-64"]
version = "25.0"

[tasks]

[dependencies]
arrow = "*"
black = "*"
bottleneck = "*"
cftime = "*"
cmocean = "*"
jupyterlab = "*"
matplotlib = "*"
nc-time-axis = "*"
netcdf4 = "*"
pixi-pycharm = ">=0.0.10,<0.0.11"
python = "3.14.*"
xarray = "*"

[feature.salishseacast-hourly-prod]
channels = ["conda-forge"]

[feature.salishseacast-hourly-prod.dependencies]
arrow = "*"
cmocean = "*"
h5netcdf = "*"
matplotlib = "*"
notebook = "*"
python = "3.13.*"
xarray = "*"
pandas-stubs = ">=2.3.3.251201,<3"

[feature.plotly-webinar.dependencies]
python = "3.14.*"
plotly = ">=6.5.2,<7"
numpy = ">=2.4.1,<3"
ipykernel = ">=7.1.0,<8"
nbformat = ">=5.10.4,<6"

[feature.plotly-nemo.dependencies]
python = "3.14.*"
ipykernel = "*"
plotly = "*"
nbformat = "*"
xarray = "*"
h5netcdf = "*"

[environments]
salishseacast-hourly-prod = { features = ["salishseacast-hourly-prod"], no-default-feature = true }
plotly-webinar = { features = ["plotly-webinar"], no-default-feature = true }
plotly-nemo = { features = ["plotly-nemo"], no-default-feature = true }
